# Generated by Django 4.1.3 on 2022-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_brand_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/main'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='описание какой-то кепке'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='какая-то кепка', max_length=100),
        ),
    ]
