# Generated by Django 4.1.3 on 2022-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_size_name_sizevariant_size_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='size_id',
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
