# Generated by Django 4.1.3 on 2022-11-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_sizevariant_size_id_sizevariant_size_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='size_id',
        ),
    ]
