# Generated by Django 4.1.3 on 2022-11-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_size_id_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
